### ISSUE TITLE
Language update

### ISSUE THREAD

**Issue by moesio-f** [moesio-f/sarlopt#2]
Translate comments, readme, docstrings, and other documentation/codes to English.

# Tasks
- [x] Translate README
- [x] Translate all modules in `experiments/baselines/`
- [x] Translate all modules in `experiments/evaluation/`
- [x] Translate all modules in `experiments/training/`
- [x] Translate all modules in `src/agents`
- [x] Translate all modules in `src/distributions`
- [x] Translate all modules in `src/environments`
- [x] Translate all modules in `src/metrics`
- [x] Translate all modules in `src/networks`
- [x] Translate all modules in `src/policies`
- [x] Translate all modules in `src/train`
- [x] Translate all modules in `src/typing`
- [x] Translate all modules in `src/utils`
- [x] Translate all modules in `src/config.py`
