### ISSUE TITLE
Add unit test to modules in `src/environments`

### ISSUE THREAD

**Issue by moesio-f** [moesio-f/sarlopt#8]
# Tasks
- [x] py_function_environment_test.py
- [x] tf_function_environment_test.py
- [ ] py_env_wrappers_test.py

**Comment by moesio-f** [comment]
#10 added py_function_environment_test.py. However, the environment relies on `numpy.random.default_rng(...)` to create a `Generator` (which doesn't guarantee compatibility). It might be interesting for the environment to store the generator being used.
